<?php

namespace App\Http\Controllers;

use App\Models\CostCenter;
use App\Models\Employee;
use Illuminate\Http\Request;
use Inertia\Inertia;

class EmployeeController extends Controller
{
    /**
     * Display a listing of employees.
     */
    public function index()
    {
        $employees = Employee::with('costCenter')
            ->orderBy('created_at', 'desc')
            ->paginate(25);

        return Inertia::render('employees/index', [
            'employees' => $employees,
        ]);
    }

    /**
     * Show the form for creating a new employee.
     */
    public function create()
    {
        $costCenters = CostCenter::active()->get();

        return Inertia::render('employees/create', [
            'costCenters' => $costCenters,
        ]);
    }

    /**
     * Store a newly created employee.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            // Employee ID - optional, if provided must be unique
            'emp_system_id' => 'nullable|string|max:50|unique:employees,emp_system_id',

            // Required fields
            'firstname' => 'required|string|max:255',
            'surname' => 'required|string|max:255',
            'emp_email' => 'required|email|unique:employees,emp_email',
            'center_id' => 'required|exists:cost_centers,id',

            // Optional fields
            'othername' => 'nullable|string|max:255',
            'phone' => 'nullable|string|max:20',
            'date_of_birth' => 'nullable|date|before:today',
            'gender' => 'nullable|in:male,female,other',
            'address' => 'nullable|string',
            'hire_date' => 'nullable|date',
            'department' => 'nullable|string|max:255',
            'position' => 'nullable|string|max:255',
            'base_salary' => 'nullable|numeric|min:0',
            'is_active' => 'boolean',
        ]);

        // If emp_system_id is not provided, it will be auto-generated by the model
        $employee = Employee::create($validated);

        return redirect()->route('employees.index')
            ->with('success', "Employee {$employee->emp_system_id} created successfully");
    }

    /**
     * Display the specified employee.
     */
    public function show(Employee $employee)
    {
        $employee->load('costCenter');

        return Inertia::render('employees/show', [
            'employee' => $employee,
        ]);
    }

    /**
     * Show the form for editing the specified employee.
     */
    public function edit(Employee $employee)
    {
        $costCenters = CostCenter::active()->get();

        return Inertia::render('employees/edit', [
            'employee' => $employee,
            'costCenters' => $costCenters,
        ]);
    }

    /**
     * Update the specified employee.
     */
    public function update(Request $request, Employee $employee)
    {
        $validated = $request->validate([
            // Employee ID - optional, if provided must be unique (except current employee)
            'emp_system_id' => "nullable|string|max:50|unique:employees,emp_system_id,{$employee->id}",

            // Required fields
            'firstname' => 'required|string|max:255',
            'surname' => 'required|string|max:255',
            'emp_email' => "required|email|unique:employees,emp_email,{$employee->id}",
            'center_id' => 'required|exists:cost_centers,id',

            // Optional fields
            'othername' => 'nullable|string|max:255',
            'phone' => 'nullable|string|max:20',
            'date_of_birth' => 'nullable|date|before:today',
            'gender' => 'nullable|in:male,female,other',
            'address' => 'nullable|string',
            'hire_date' => 'nullable|date',
            'department' => 'nullable|string|max:255',
            'position' => 'nullable|string|max:255',
            'base_salary' => 'nullable|numeric|min:0',
            'is_active' => 'boolean',
        ]);

        $employee->update($validated);

        return redirect()->route('employees.index')
            ->with('success', "Employee {$employee->emp_system_id} updated successfully");
    }

    /**
     * Remove the specified employee (soft delete).
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect()->route('employees.index')
            ->with('success', "Employee {$employee->emp_system_id} deleted successfully");
    }

    /**
     * Terminate an employee.
     */
    public function terminate(Request $request, Employee $employee)
    {
        $validated = $request->validate([
            'is_ex_on' => 'required|date',
        ]);

        $employee->update([
            'is_ex' => true,
            'is_ex_on' => $validated['is_ex_on'],
            'is_active' => false,
        ]);

        return redirect()->route('employees.index')
            ->with('success', "Employee {$employee->emp_system_id} terminated successfully");
    }
}
